version: '3.7'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
  client:
    build: ./client
    container_name: client
    depends_on:
      - server
